#!/usr/bin/env python3
"""Print the Homebrew formula for a schemaviz release, from that release's SHA256SUMS.

    scripts/homebrew-formula.py 0.1.0 > Formula/schemaviz.rb      # then commit it to the tap

Reads SHA256SUMS from the GitHub release (public, so no token). Uses the raw binaries the release workflow uploads.
"""
import os
import sys
import urllib.request

REPO = "phin-tech/skills"
ASSETS = {  # (os block, cpu block) -> asset
    ("macos", "arm"): "schemaviz-darwin-arm64", ("macos", "intel"): "schemaviz-darwin-x64",
    ("linux", "arm"): "schemaviz-linux-arm64", ("linux", "intel"): "schemaviz-linux-x64",
}


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    version = sys.argv[1].removeprefix("v")
    base = f"https://github.com/{REPO}/releases/download/schemaviz-v{version}"
    where = os.environ.get("SCHEMAVIZ_SUMS_BASE", base)  # a file:// directory, for testing
    sums = {}
    for line in urllib.request.urlopen(f"{where}/SHA256SUMS").read().decode().splitlines():
        digest, _, name = line.partition("  ")
        sums[name.strip().lstrip("*")] = digest
    missing = [a for a in ASSETS.values() if a not in sums]
    if missing:
        raise SystemExit(f"SHA256SUMS for {version} has no entry for: {', '.join(missing)}")
    out = ["# Generated by skills/schemaviz/scripts/homebrew-formula.py from the release's SHA256SUMS. Do not edit by hand.",
           "class Schemaviz < Formula",
           '  desc "Draw a database schema, and what a migration changed, as an interactive page"',
           f'  homepage "https://github.com/{REPO}/tree/main/skills/schemaviz"',
           f'  version "{version}"',
           '  license "MIT"', ""]
    for os_block in ("macos", "linux"):
        out.append(f"  on_{os_block} do")
        for cpu in ("arm", "intel"):
            asset = ASSETS[(os_block, cpu)]
            out += [f"    on_{cpu} do", f'      url "{base.replace(version, "#{version}")}/{asset}"', f'      sha256 "{sums[asset]}"', "    end"]
        out += ["  end", ""]
    out += ["  def install", '    bin.install(Dir["schemaviz-*"].first => "schemaviz")', "  end", "",
            "  test do",
            '    assert_match "schemaviz #{version}", shell_output("#{bin}/schemaviz --version")',
            '    (testpath/"s.dbml").write("Table t { id integer [pk] }\\n")',
            '    system bin/"schemaviz", "render", "s.dbml", "--out", "s.html", "--expect", "1"',
            '    assert_path_exists testpath/"s.html"',
            "  end", "end"]
    print("\n".join(out))


if __name__ == "__main__":
    main()
